### ISSUE TITLE
[Bug] Unable to approve addons

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#100]
### What happened?

Title.

### To reproduce

1. Go to the Add-on Review tab
2. Find a pending add-on (currently Coloured Sheep)
3. Click the approve button
4. Nothing happens

### Browser name and version

Firefor 105.0.1

### Logs

![obrazek](https://user-images.githubusercontent.com/59484948/194428449-9565e370-a758-4f69-8b29-23537085d2ef.png)

**Comment by 3vorp** [comment]
firefor

**Comment by TheRolfFR** [comment]
my bad, I forgot some code
