### ISSUE TITLE
[Bug] Add-on review notifications don't disappear after add-ons are reviewed

### ISSUE THREAD

**Issue by 3vorp** [Faithful-Resource-Pack/App#101]
### What happened?

So basically if there are pending addons that need review/approval, and you approve/deny them, the badge that shows that there are new addons doesn't go away until you refresh the page.

### To reproduce

1. Go to https://webapp.faithfulpack.net/#/review/addons when there are pending add-ons (requires manager permissions)
2. Approve or deny the add-on
3. Go anywhere else in the webapp
4. Observe that the red dot badge thingy doesn't disappear

### Browser name and version

Regular Google Chrome - Version 106.0.5249.119

**Comment by Pomi108** [comment]
Can't reproduce, didn't happen to me last time i reviewed addons.

**Comment by TheRolfFR** [comment]
It is refreshed every 30s, so if you don't mind waiting, it will disappear

**Comment by 3vorp** [comment]
ah ok
