### ISSUE TITLE
Do not truncate texture paths in the use/path editors

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#107]
### What happened?

The web app always trims off the `assets/minecraft/` from all Java paths, even though that prefix is still present in the database. Since the prefix is needed for the path to work correctly, truncating the paths in the web app only causes issues. 
Luckily this only seems to be a display issue, since pasting the full path when creating it adds it to the database properly.

### To reproduce

1. Go to the Textures tab
2. Search for a texture
3. Press the edit button
4. Edit the use
5. See that the paths are being truncated

### Screenshot(s)

![obrazek](https://github.com/Faithful-Resource-Pack/App/assets/59484948/4ec46c7c-8001-4d44-bb55-b37678a4bb0d)
![obrazek](https://github.com/Faithful-Resource-Pack/App/assets/59484948/2a69f7dd-2199-4b84-99f1-5cf05844ed4a)

### Browser name and version

Not relevant.

**Comment by Pomi108** [comment]
The path is still truncated in the path editor
![obrazek](https://github.com/Faithful-Resource-Pack/App/assets/59484948/d456cb66-18c8-447a-94db-f87325904611)

**Comment by TheRolfFR** [comment]
This how it is stored in db
![image](https://github.com/Faithful-Resource-Pack/App/assets/18086786/7c82aebe-6d69-48a7-bd36-50b65d4fdabf)
More details here https://github.com/Faithful-Resource-Pack/App/issues/92#issuecomment-1214142494
No modification is made.

**Comment by Pomi108** [comment]
oh, right. forgot juknum did that

**Comment by TheRolfFR** [comment]
What should we do them for this issue?

**Comment by Pomi108** [comment]
Nothing for now I guess – what the path editor displays now is correct, after all
When [this issue](https://github.com/Faithful-Resource-Pack/API/issues/28) is fixed and the database format changed, I think we'll have achieved the ideal outcome

**Comment by 3vorp** [comment]
fixed with recent api changes
