### ISSUE TITLE
[Bug] Adding multiple textures at once behaves very weirdly

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#115]
### What happened?

Self-explanatory. Adding a single texture works fine, but once you try to add two or more at once, you get an error.

Observations:
- ~~When the error appears, the textures produced from this attempt are visible when searching the database using the Textures tab and in the gallery, but you can't find them with the the bot~~ Nevermind that is a bot issue. Gonna report that too
- The error seems to be fake? The textures seem to be added properly no matter if an error is thrown or not
- Sometimes it just works and throws no error

### To reproduce

1. Go to the Textures tab
2. Add a texture
3. In the Add new textures modal, specify two or more textures
4. Save
5. Web app errors out

### Screenshot(s)

![obrazek](https://github.com/Faithful-Resource-Pack/App/assets/59484948/4ed209b9-dd0b-43bd-9011-90e664c3af94)

### Browser name and version

- Firefox 119.0.1

### Logs

![obrazek](https://github.com/Faithful-Resource-Pack/App/assets/59484948/01194cd4-8735-429b-b04a-86f69ac2776e)

**Comment by Pomi108** [comment]
More observations:
Attempting to add a single texture with multiple paths produced an error; the texture was created properly, however only the second path specified was added

**Comment by 3vorp** [comment]
makes sense given that the error was a path related error

**Comment by TheRolfFR** [comment]
Linked with PR https://github.com/Faithful-Resource-Pack/API/pull/38
