### ISSUE TITLE
[Bug] Editing various things throws a "fake" error

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#118]
### What happened?

Trying to edit any use-wide information throws a 404 axios error, even though the edited information seems to be saved properly.

### To reproduce

1. Go to the Textures tab
2. Search for a texture
3. Edit it, get to the edit use modal
4. Change some info
5. Try to save it
6. Axios error

### Screenshot(s)

![obrazek](https://github.com/Faithful-Resource-Pack/App/assets/59484948/01970d45-0cb4-4d17-9f35-c09d282c3d68)

### Browser name and version

Firefox 120

### Logs

![obrazek](https://github.com/Faithful-Resource-Pack/App/assets/59484948/36e967c0-1310-41dc-8c36-ef55b6c1ec42)

**Comment by Pomi108** [comment]
This applies to use creation as well (error is thrown, but the use is created properly)

**Comment by Pomi108** [comment]
Texture creation is also affected by this bug

**Comment by TheRolfFR** [comment]
Should be fixed too by https://github.com/Faithful-Resource-Pack/API/pull/38, check after merge if still occuring
