### ISSUE TITLE
[Bug] Paths fail to get added upon texture creation

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#119]
### What happened?

When creating a texture, the texture and the first use is created properly, however any paths you enter will be disregarded.

### To reproduce

1. Go to the textures tab
2. Add a texture
3. Add an use with a path to it
4. Create the texture
5. Look it up
6. View its paths
7. None were saved

### Browser name and version

Firefox 120

**Comment by TheRolfFR** [comment]
Depends on #120
