### ISSUE TITLE
[Bug] Only the first use is saved upon texture creation

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#120]
### What happened?

When creating a texture, only the first use from the list gets saved and created at all. Any further ones are disregarded.

### To reproduce

1. Go to the textures tab
2. Create a texture
3. Add more than 1 use to it
4. Create the texture
5. Look it up
6. Only one use was saved

### Browser name and version

Firefox 120

**Comment by TheRolfFR** [comment]
Found one thing, maybe not the whole thing, @3vorp made a modification which gets the use after creating it:
![image](https://github.com/Faithful-Resource-Pack/App/assets/18086786/c6d3630f-ecd3-4501-98de-30838a8b425b)
but ``id`` variable returned in the anonymous function is not the id, it's a JSON success message

**Comment by TheRolfFR** [comment]
I've also limited the number of request to firestorm to create full textures with now 1 request for all the uses, and 1 request for all the paths
