### ISSUE TITLE
Unable to change profile information

### ISSUE THREAD

**Issue by Quarthe** [Faithful-Resource-Pack/App#125]
### What happened?

Whenever I go to save any changes I make to my profile I get this error

Request failed with status code 422:
Validation FailedWhenever

### To reproduce

Open Profile
Make any changes (Username, Valid Minecraft UUID, Social Media link)
Click Save
"Request failed with status code 422: Validation Failed" Appears on the bottom right
Nothing gets saved

### Screenshot(s)

 ![image_2024-02-19_181747985](https://github.com/Faithful-Resource-Pack/App/assets/82123436/9b895c7e-b354-4952-a413-283b000c5330)

### Browser name and version

Opera GX - LVL5 (core: 107.0.5045.30)
               System: Windows 10 64-bit
               Chromium version:121.0.6167.160

Google Chrome - Version 121.0.6167.185 (Official Build) (64-bit)

### Logs

Opera GX  ![image_2024-02-19_182043996](https://github.com/Faithful-Resource-Pack/App/assets/82123436/cd2f4fe9-b004-47ee-b6a6-4046c6f8c97a)

Google Chrome ![image_2024-02-19_183641705](https://github.com/Faithful-Resource-Pack/App/assets/82123436/70852f33-c1a3-444b-a838-27467dbadc3c)

**Comment by TheRolfFR** [comment]
Solved by https://github.com/Faithful-Resource-Pack/API/commit/066ae40572910c489c58083da5bf3d10a7386ba5
