### ISSUE TITLE
[Feature]  - add an automatic bedrock use button

### ISSUE THREAD

**Issue by DMgaming100** [Faithful-Resource-Pack/App#128]
### Describe the feature you'd like

If a texture only has a single java path, then have a second button under `add new use`, called `add automatic bedrock use`
which would automaticly add a bedrock tag and a bedrock use with a path based on the java path.

So in this example, wolf_ashen only has one java path, so clicking the button would take the path [assets/textures/entity/wolf/wolf_ashen.png] and make a bedrock use with the bedrock path [textures/entity/wolf/wolf_ashen.png]

of course, this would require the person to know for sure that the java and bedrock paths are identical (other than stuff like bedrock files ending with s)

this could save a lot of time instead of having to write down a use and a path each time, for many textures

### Screenshot(s)

![concept](https://github.com/Faithful-Resource-Pack/App/assets/79250932/a8b3f0bd-bc61-4d31-be9d-fb9ee7f203bd)

**Comment by TheRolfFR** [comment]
I think it is not very hard.

I would suggest a flat expansion pattern which, when expanded, loads into input fields the preview of the added items but editable to let user do corrections if desired.

Important question: Do you have to do this on many textures at once or only texture by texture?

**Comment by DMgaming100** [comment]
Texture by texture would be fine I think

**Comment by DMgaming100** [comment]
also, would be useful to have a button like it here too
![image](https://github.com/Faithful-Resource-Pack/App/assets/79250932/4065ca17-2cf7-4180-9bee-6bab1cf5a779)
