### ISSUE TITLE
[BUG] - MC version in settings.json isn't updated after version update from the webapp

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/App#17]
**Describe the bug**
When updating a Minecraft version through the webapp, all paths are successfully changed, but the versions inside `settings.json` remains the same, which, doesn't allow us to edit/add this edited version to existing/new textures.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the texture tab in the database menu
2. Click on `modify a Minecraft version`
3. Set a new field
4. Refresh the page
5. Open any texture & go to its path, see the path using the field you've edited
6. Edit the version of that path, you can't see the edited path you've added;

**Expected behaviour**
Settings.json being smoothly updated

**Screenshots**
Should be implemented somewhere here
https://github.com/Compliance-Resource-Pack/App/blob/main/backend/paths.js#L87

**Additional context**
⚠️ This also happens with adding a new version!!

**Comment by Juknum** [comment]
MC Versions should be moved to the versions collections, thus allowing us to directly modify it easily without modifying the whole settings collection

**Comment by 3vorp** [comment]
tbh I don't even think we need to store the version list in settings.json? like we can just do what we did with texture tags and just reduce the path collection to just the unique versions and return that as an endpoint, since tbh rn it's just duplicate

**Comment by 3vorp** [comment]
completed with https://github.com/Faithful-Resource-Pack/API/commit/170fad639530ef1e58e791e5cc093e783d7e86a0
