### ISSUE TITLE
Add mods/modpacks edit & submit to the webapp

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/App#19]
- [x] Make a database collection for mods & modpacks, this would fix not founds mods when downloading modpacks resources pack (this would use ID instead of names)
- [x] Use CurseForge project ID for mods ID (todo: find a solution for mods not on curse)

- [ ] Add support for Modrinth & others platform

**Comment by TheRolfFR** [comment]
I am closing this for now since we clearly have no intention to do that soon
