### ISSUE TITLE
Implement a page for colors/color palettes:

### ISSUE THREAD

**Issue by Juknum** [Faithful-Resource-Pack/App#20]
- based on features from https://coolors.co/
- implement into the current bot commands (/color and /palette)

(main reason for this being, that coolors.co, the current service that we use is bloated with many features that we don't actually need)

**Comment by 3vorp** [comment]
is this needed anymore? honestly the entire coolors integration is kinda unnecessary within the bot anyways since it's only used on one specific embed and I don't even think anyone clicks those links (correct me if I'm wrong)

**Comment by Pomi108** [comment]
Yeah imo this isn't really something that belongs on any of our pages at all

**Comment by 3vorp** [comment]
cool then I'll close it
