### ISSUE TITLE
[BUG] - Only one path from textures with multiple paths in a single edition and version is searchable

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#25]
**Describe the bug**
Take for example the dirt texture. For Compliance purposes, the texture has been merged with `options_background` and thus multiple java paths (in a single version) are assigned to the texture ID. However, searching for `options_background` in the gallery yields no results.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the gallery
2. Search for any texture that has multiple paths assigned to the ID in a single edition and version
3. No results when searching for any texture name other than the first (?)

**Expected behaviour**
The gallery should show these "merged" textures separately (they should still be listed as one ID with multiple paths though – the issue is with the search output). As in, the gallery should search the paths themselves, not just the IDs.

**Screenshots**
![Snímek obrazovky 2022-01-26 v 21 48 33](https://user-images.githubusercontent.com/59484948/151244952-63399661-f6ec-4927-be3a-9f4d97770547.png)

**Comment by 3vorp** [comment]
the reason why this isn't the case to the best of my knowledge is that searching paths is very "expensive" — you first have to find the texture uses, then find the paths of those uses, then scan a field in those paths with a partial search — compare this to simply searching one field of that first texture interface

the closest thing I could think of that would work well is a "keyword" system, where you could search for one or multiple keywords for a texture, but that's also a huge pain to create and would have a lot of breaking changes on the api end

**Comment by Pomi108** [comment]
this is a very old issue from a time when i didn't fully understand the database yet... I don't think it's feasible to implement anything that would resolve this with the web app in its current state. This issue should probably be closed, or at the very least marked as a feature request instead of a bug

**Comment by 3vorp** [comment]
not really? do remember that now that the jsons are updated to api v2, it's very possible to _add_ fields, just annoying to modify or delete them

however, yeah this isn't feasible to implement since someone would have to go through and add all the duplicate names
