### ISSUE TITLE
[BUG] Incorrect display of non-existent textures in gallery

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#36]
**Describe the bug**
When searching for a texture name that doesn't exist in the gallery, instead of showing the usual `No results found.` text, a weird rectangle is shown instead.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://webapp.faithfulpack.net/#/gallery/java/32x/1.18.2/All/break_particle for example.
2. Observe the rectangle.

**Expected behaviour**
A text saying `No results found.` should be shown.

**Screenshots**
![Snímek obrazovky 2022-04-16 v 12 01 24](https://user-images.githubusercontent.com/59484948/163670756-f70904ef-5564-4b7a-aaf8-c3f3351f3d42.png)

**Browser & Environment (computer/phone):**
 - Firefox
 - 99.0.1

**Logs**
No logs are generated.

**Comment by Juknum** [comment]
Can't reproduce on Safari (iOS)
![image](https://user-images.githubusercontent.com/49886317/163671649-9d55acf9-9fc9-4a3b-8e75-ac89ec8a05d1.png)
