### ISSUE TITLE
[REQUEST] Allow defining date format in translations

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#41]
When using a translation, the standard English date format is still used, which might be incorrect in some languages. It would be very useful to have the ability to define a custom date format for each language.

**Comment by Pomi108** [comment]
Not sure how, but all languages seem to be using the correct format now

**Comment by TheRolfFR** [comment]
Yes I have done it for #45 and improved more recently 9bcc0d4, I am closing this issue

**Comment by Pomi108** [comment]
Reopening since the correct date format still isn't used when hovering over textures in the gallery

**Comment by Pomi108** [comment]
I'm so sorry… reopening this again since nothing seems to have changed… yes I've hard-refreshed, even opened the web app in chrome

**Comment by Juknum** [comment]
Can you send a screenshot of where it's happening?

**Comment by Pomi108** [comment]
Tomorrow

**Comment by Pomi108** [comment]
![Snímek obrazovky 2022-04-24 v 9 41 04](https://user-images.githubusercontent.com/59484948/164965763-23ea9a9b-d4e1-456d-9af7-8895b6b984cc.png)

**Comment by Pomi108** [comment]
This has been fixed now.
