### ISSUE TITLE
[BUG] Anonymous option is completely broken

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#42]
**Describe the bug**
The Anonymous option in user settings straight up doesn't work at all. Even when it's not checked, the name is still shown everywhere.

Additionally, instead of users not in the database showing as `Unknown user`, they show up as `Anonymous` instead.

**To Reproduce**
Steps to reproduce the behaviour:
1. Check the `Anonymous` checkbox in the user settings of any user
2. Go to the gallery and search for a texture they're credited for
3. Observe their name being shown

**Expected behaviour**
The name should be censored and show `Anonymous`. Users not in the database should be displayed as `Unknown user`.

**Screenshots**
![Snímek obrazovky 2022-04-16 v 22 22 22](https://user-images.githubusercontent.com/59484948/163690352-25824d54-fefa-4221-b593-8ea5d6f722e9.png)
![Snímek obrazovky 2022-04-16 v 22 22 18](https://user-images.githubusercontent.com/59484948/163690353-5ffeedf8-dd3d-4f08-a98c-eb18f8f1c53b.png)

**Browser & Environment (computer/phone):**
 - Firefox
 - 99.0.1

**Comment by Juknum** [comment]
Found out, API changes aren't deployed yet

**Comment by Juknum** [comment]
Should be fixed in [1cfee5f](https://github.com/Faithful-Resource-Pack/API/commit/1cfee5f3841bc911d0b20d8d31f8a5c68923f9e0) (Re-open if not, be sure to hard refresh first)
