### ISSUE TITLE
[BUG] Issues with contribution listing when a user has a lot of them

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#43]
**Describe the bug**
On the Contributions page, when searching for a person's contributions, the texture names and all the authors related to the contribution were listed as well. This is, however, no longer the case.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the Contributions page
2. Search for the contributions of any contributor
3. See only the date and ID being listed

**Expected behaviour**
The name of the texture should be shown, along with all the authors related to the contrib, as that's useful when there are multiple authors.

**Screenshots**
![Snímek obrazovky 2022-04-16 v 22 47 49](https://user-images.githubusercontent.com/59484948/163690957-d0f9c7e2-e841-42f5-9fc8-a20a3757a375.png)

**Browser & Environment (computer/phone):**
 - Firefox
 - 99.0.1

**Comment by Pomi108** [comment]
Reopening because texture names are still not being shown, also the authors should probably be shown on a separate line :P
![Snímek obrazovky 2022-04-19 v 19 51 06](https://user-images.githubusercontent.com/59484948/164065344-be088413-792e-4b8d-8e67-58d5f2bc175a.png)

**Comment by Juknum** [comment]
@Pomi108 Did you hard-refreshed?

**Comment by Pomi108** [comment]
Yeah, of course, multiple times.

**Comment by Pomi108** [comment]
Update: The line breaks now work properly, but texture names still aren't shown

**Comment by Juknum** [comment]
They might not show if there is a lot of them, try with someone with less contributions (>20)

**Comment by Pomi108** [comment]
you're right, when i search for AyakamaHeruka's contribs (they've got 8 total) the names show up properly

**Comment by Juknum** [comment]
That's because names are fetched for each texture and not all at the same time (I haven't done such API thing yet)

**Comment by TheRolfFR** [comment]
You're getting softbanned with a Cloudflare message, and I don't know why we are making so much requests:
![image](https://user-images.githubusercontent.com/18086786/166098878-b0725414-0355-40ed-a249-21ce506e89fb.png)

Nevertheless I don't think the error is generated by Cloudflare.
Research led me to ![this article](https://webpop.io/cloudflare/502-bad-gateway-error/), which seems coherent:
![image](https://user-images.githubusercontent.com/18086786/166099089-cdd65cd6-c77f-4eb0-9584-9665bd1550dd.png)

I suppose the solution is to decrease the f****** number of requests made

**Comment by Juknum** [comment]
Yeah the solution is to implement all requests into 1 big request instead; but I didn't had the time to do it at first.

**Comment by Pomi108** [comment]
if this does what i think it does then THIS IS THE BEST DAY OF MY LIFE

**Comment by Pomi108** [comment]
This seems to happen again. Reopening

**Comment by Pomi108** [comment]
![Snímek obrazovky 2022-06-19 v 12 54 23](https://user-images.githubusercontent.com/59484948/174477501-842d1cb7-05c3-48ef-a3d8-e93192bf48cf.png)

**Comment by Pomi108** [comment]
This doesn't seem to be an issue anymore. Haven't had any troubles with the contributions page for a long time now so I'm closing this as completed
