### ISSUE TITLE
[REQUEST] Move language selection controls somewhere else

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#46]
Right now, the controls for language switching are always at the bottom of the page. But since many pages like the gallery or contributions are very long, it can require the user to scroll very far down to reach the controls. The gallery is the most annoying page of them all, since oftentimes you'll reach the "bottom", reach for the controls but then more textures load and you have to scroll again.

This is why I think the controls should be moved somewhere else. Perhaps to the top of the page to the navbar?

**Comment by Juknum** [comment]
This is related to #38
