### ISSUE TITLE
Addon Submission Fails with Image Extension ".PNG"; Works with ".png"

### ISSUE THREAD

**Issue by copy-cancel** [Faithful-Resource-Pack/App#55]
**Describe the bug**
When submitting addons on the web app, this error shows and prevents submitting the new addon when the header image has a capitalized PNG extension: "Request failed with status code 403: Extension not allowed."

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a new addon submission in the web app.
2. Upload a header image with extension ".PNG".
3. Fill in all required fields.
4. See the error when clicking the "Submit" button.

**Expected behaviour**
There should be no error, since ".PNG" should be treated exactly as ".png".

**Screenshots**
![image](https://user-images.githubusercontent.com/90941923/165981013-be49798e-fdb4-4b4d-9c6d-3487fb7ee936.png)

**Browser & Environment (PC):**
 - Browser = Google Chrome
 - Version 100.0.4896.127 (Official Build) (64-bit)

**Logs**
You might want to collect this on your own.

**Comment by nick-1666** [comment]
can we not add an i at the end of our regex for case insensitivity?

**Comment by TheRolfFR** [comment]
It's a Firestorm problem, and I don't consider it really as a bug, I added uppercase extensions in authorized file extensions in the config file.
It works now, I am closing this issue
