### ISSUE TITLE
[FEATURE] - Missing Tag in Gallery

### ISSUE THREAD

**Issue by TheRandomGamrTRG** [Faithful-Resource-Pack/App#56]
A missing tag that can be used to find which textures are yet to be completed. Basically /missing but on the gallery.

**Describe the solution you'd like**
If possible, the tag could be automatically assigned and removed depending on whether or not a texture for 32x or 64x exists. Seperate tags for 32x, 64x, bedrock etc could also be used.

**Describe alternatives you've considered**
I don't have any alternatives, but anyway to find a list of missing textures on the gallery.

**Additional context**
N/A

**Comment by 3vorp** [comment]
Given that it's not really viable to check whether an image exists for every texture and every pack in the DB basically every day, I'm gonna close this.
