### ISSUE TITLE
[FEATURE] - Allow specific pages to be seen without needing to log in

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Resource-Pack/App#57]
Some pages are just unnecessary to be logged in to access them.

Some of these pages that should be publicly accessible are:
- Dashboard (would need a replacement for the "Profile" widget
- Statistics
- Gallery

The gallery page likely being to most used one by people who don't actually need to do anything with their linked account.

**Comment by Juknum** [comment]
@TheRolfFR @RobertRR11 is this done?
