### ISSUE TITLE
[BUG] - Updating your Discord profile picture breaks various things

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Resource-Pack/App#58]
Unfortunately I don't have any screenshots anymore, but updating your Discord profile picture does following things in the webapp:
- The webapp profile picture doesn't load at all anymore
- breaks loading of pending and denied add-ons in the reviews section
- possibly more that I haven't seen yet

All of this fixes itself after logging out and back in again, but this issue should still be looked into.

**Comment by Pomi108** [comment]
Can confirm, this issue happened to me as well when I changed my profile picture.

**Comment by Juknum** [comment]
I don't know if it's possible to notify the webapp when we changes our profile picture; might be better to refetch it each time we load the app? But then multiple questions goes out:

- add a way to not do it for each time we navigate (to avoid data consumption to go ⤴️)
- might cause issue with the refresh token

**Comment by TheRolfFR** [comment]
Yes, that is what I would do, I was surprised when I saw that you store this data. The only thing I would store is the discord token and refresh token

**Comment by TheRolfFR** [comment]
Since e22811c, discord banner is not stored and fetched at webapp startup. Could you configure this bug is still happening?

**Comment by RobertRR11** [comment]
Just confirmed that the issue doesn't happen anymore
