### ISSUE TITLE
All languages are loaded even though none are being selected

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Resource-Pack/App#59]
I wouldn't call this a bug, but probably more of an oversight. All language files are being loaded even though just the one that is activated should be. These files are pretty small, but scaling that to hundreds of users and many page visits per session definitely results in a lot of unnecessary traffic.

This is a screenshot from the chrome dev tools in the network tab:
![image](https://user-images.githubusercontent.com/57044042/170828071-d4b063ec-0079-41d1-a5d8-03f233f8e181.png)

**Comment by TheRolfFR** [comment]
Might be more of a feature because we are just loading all languages like dumb asses instead of being smart https://github.com/Faithful-Resource-Pack/App/blob/9bc4e295505505be008e4c8680dea4c84826b1d2/compliapp.js#L98-L102

**Comment by RobertRR11** [comment]
yeah that definitely shouldn't be done like that
