### ISSUE TITLE
[FEATURE] Add a way to add new or modify existing texture tags

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#62]
This would be useful for sorting textures into more categories, for example all banner textures (which currently can't be searched for all at once) would be given a single shared Banner tag.

**Comment by 3vorp** [comment]
honestly I don't even think there's any verification for creating tags, I'm like 99% sure if you created a new texture manually and added a custom tag the DB would just accept it and show it from then on
