### ISSUE TITLE
[FEATURE] Add a way to search for contributions by texture instead of just the user

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#63]
Currently, the only way to search for contributions is by user. Since many users have a lot of contributions to their name, this puts a lot of stress on the app and it often fails (see #43). Being able to search for a specific texture only would bypass all of this and is almost guaranteed to never fail, since any given texture will only need to list tens of contributions at most (compared to hundreds for a contributor).

**Comment by TheRolfFR** [comment]
So I made that:
![image](https://user-images.githubusercontent.com/18086786/185584472-c27ab468-5a64-46d8-9678-9421173bb800.png)
What do you think?

When you say search by texture instead of just user, do we keep the user mandatory and make the texture search optional, can we search just with a texture?

**Comment by Pomi108** [comment]
This is great! Yeah it would be ideal to make the user search optional

**Comment by TheRolfFR** [comment]
![image](https://user-images.githubusercontent.com/18086786/185683182-d8b78721-d2eb-433f-94cd-10873e937d28.png)

This seems to work fine, any additional things to add?

**Comment by Pomi108** [comment]
Hmm, perhaps searching by ID like in the gallery?

**Comment by TheRolfFR** [comment]
Damn API was already able to do it, just needed to adjust button disabled
![image](https://user-images.githubusercontent.com/18086786/185706193-1b66510b-f741-48b2-b992-2d6bdba403cc.png)

**Comment by Pomi108** [comment]
Nice, I think it's perfect now
