### ISSUE TITLE
[FEATURE] Add side margins to the gallery again

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#64]
Please do this. The gallery is too stretchy. All other pages have side margins as well. Why be inconsistent?

**Comment by Juknum** [comment]
I'll prefer having a slider / a way to choose how many textures should be display per rows

**Comment by Pomi108** [comment]
Works for me

**Comment by TheRolfFR** [comment]
@Pomi108 @Juknum Any improvements we could do ?

**Comment by Pomi108** [comment]
I think it's fine now. I got used to it
