### ISSUE TITLE
[FEATURE] Define whether a texture is animated per texture instead of per path

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#69]
I was pretty surprised when I found that at the moment the DB defines whether a texture is animated or not in every path. Why not have the whole texture define that, since multiple paths within one texture always point to an identical image file?

**Comment by Juknum** [comment]
That's mainly because the mcmeta file isn't there on bedrock edition, so bedrock path should be set to false (to avoid any issue) but yeah it might be better implemented

**Comment by Pomi108** [comment]
I see what you mean, but the bedrock files can just use the java mcmeta if it's really needed i guess

**Comment by TheRolfFR** [comment]
I thought it was on the use and not on the path?

**Comment by Pomi108** [comment]
Just double-checked, and it is indeed stored on the path, not on the use.

**Comment by 3vorp** [comment]
ok so I actually looked into this and it's really useful to have animated stuff stored on the path since that was you can guarantee an mcmeta will be present to fetch, putting it on the use can result in misleading results and weird edge cases from bad setup so I'd honestly rather keep it there
