### ISSUE TITLE
[FEATURE] Sort textures in gallery alphabetically based on their name instead of by ID

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#72]
When the database was first created, the IDs matched the alphabetical order of the files in the Minecraft folder structure. Over time though, many textures have been added and removed, either to add content from new versions or to address issues. Since the gallery currently sorts textures by ID, this can result in unhelpful placement of groups of textures that have one or more texture with a comparatively very new ID – such as cocoa beans – when viewed among a large set of other textures (like when browsing through all of them).

**Comment by TheRolfFR** [comment]
Could you check please and close if done?

**Comment by Pomi108** [comment]
How long do I need to wait for the changes to appear?

**Comment by TheRolfFR** [comment]
i cleared cache results so once API is deployed and restarted
