### ISSUE TITLE
[BUG] - Drag dropping images into the add-on creator doesnt work

### ISSUE THREAD

**Issue by ewanhowell5195** [Faithful-Resource-Pack/App#79]
Drag dropping images into the add-on creator doesnt work. It just opens them in a new tab.

**Comment by TheRolfFR** [comment]
The file input is just a regular input, not a drag and drop one

**Comment by ewanhowell5195** [comment]
@TheRolfFR hmmmmmmmmm
![image](https://user-images.githubusercontent.com/48070995/177962754-7fc8cb04-3916-4c8c-abcf-15489751230d.png)

**Comment by RobertRR11** [comment]
I'm sure dropping images had actually worked sometime
