### ISSUE TITLE
[FEATURE] Compare textures of programmer art projects against PA textures in the gallery menu

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#83]
Since we now have programmer art branches on the Default-Java repo for versions ≥1.14, those should be displayed as the 16x image when you click a texture after searching for it in a programmer art project (currently only CF32PA), instead of the jappa texture that's used at the moment.

**Comment by TheRolfFR** [comment]
Do you mean the preview in the modal ? 
You want the PA previews next to the 16x art if you are looking at a programmer art?

**Comment by Pomi108** [comment]
Well, since we show both types for higher resolutions now, I think we should show both the jappa and programmer art texture in the gallery modal.

If a texture doesn't have a programmer art equivalent, then showing the standard "texture is missing" text would be fine.

**Comment by Pomi108** [comment]
This was implemented at some point but this issue was never closed
