### ISSUE TITLE
[Bug] Contributions cannot be added or edited anymore

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#90]
### What happened?

When trying to add or modify a contribution, an error 400 is thrown.

### To reproduce

1. Go to Contributions
2. Try to add a new one or modify an existing one
3. See the error

### Screenshot(s)

![Snímek obrazovky 2022-08-01 v 22 24 56](https://user-images.githubusercontent.com/59484948/182243397-cda5d8ef-8254-4e4b-b683-e024abb61fe2.png)

### Browser name and version

Firefox 103.0

**Comment by Pomi108** [comment]
Update: Deleting contributions seems to be working fine

**Comment by TheRolfFR** [comment]
You still have the bug @Pomi108?

**Comment by Pomi108** [comment]
Don't have anything to test it on right now, but last time I used the app this seemed to be fixed, so I'm closing the issue.
