### ISSUE TITLE
[Feature] Sort authors the opposite way in the texture modal

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#91]
### Describe the feature you'd like

Right now, in the Authors tab of the gallery texture modal, authors are sorted in such a way that older contributions come first. I think it should be sorted inversely, so that newer contributions are at the top.

**Comment by TheRolfFR** [comment]
I am fixing it on main, but @Juknum you should do it too in the rework

**Comment by Pomi108** [comment]
Was this commit supposed to fix it? Because I'm still seeing the old sort order on my end.

**Comment by Pomi108** [comment]
Nevermind, it seems to be working now.
