### ISSUE TITLE
[Feature] Require users to set a profile username before submitting add-ons

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#93]
### Is your feature request related to a problem?

I reviewed an add-on submission today, and noticed that oftentimes the user will be listed as `Unknown User` because they're not registered in the database yet. This makes it a bit annoying, because I have no way of contacting the add-on author elsewhere, should I need to do so.

### Describe the feature you'd like

The app should simply require everybody to assign a username to themselves before they're allowed to submit anything.

### Notes

I'm not 100% sure if this isn't the case already. Either way, the `Unknown User` issue is a real thing.

**Comment by TheRolfFR** [comment]
I wanted to do this correctly, so I added securities on the webapp to prevent empty usernames:
![image](https://user-images.githubusercontent.com/18086786/185785670-2833e407-7476-4671-b3c5-71fdeaff3cf6.png)

And I added some verification on the API side when updating the profile side to verify that the trimmed version of the username is not empty:
![image](https://user-images.githubusercontent.com/18086786/185785675-077ce886-b9d6-4694-bd7e-a142ec257c4e.png)

Eventually I added some verifications when creating or updating an add-on also checking authors usernames (there is a case where the profile was just created but never modified in the profile page so there is no username yet):
![image](https://user-images.githubusercontent.com/18086786/185785906-6385a434-a2ce-4be7-896e-d308fa96343c.png)

**Comment by RobertRR11** [comment]
Or maybe just set a default username, because we're logging in with discord here

**Comment by TheRolfFR** [comment]
we could do that in addition when creating the profile, but I am not reopening the issue
