### ISSUE TITLE
[Bug] when adding a download link to add-ons, apostrophes make the url invalid

### ISSUE THREAD

**Issue by RobertRR11** [Faithful-Resource-Pack/App#95]
### What happened?

When adding a download link to an add-on and using an apostrophe in the file name, the url is made invalid, evne though apostrophes can be used in file names.

### To reproduce

1. go to the upload page for add-ons
2. add a download
3. type in a url which includes an apostrophe

### Screenshot(s)

![image](https://user-images.githubusercontent.com/57044042/184550253-acbcade0-cc68-4ffd-ae52-92c9e5264424.png)
![image](https://user-images.githubusercontent.com/57044042/184550259-ee839533-0015-40e3-9331-18cb74fa7db2.png)

### Browser name and version

any

**Comment by Juknum** [comment]
Apostrophe might not be considered as a safe character by the validation script

**Comment by TheRolfFR** [comment]
In general, the single apostrophe is not considered a safe character and must be encoded (%27) to avoid injection, as a result, I would prefer not to change the regex and rather forbid this character completely, as a result I think it is not a good idea to fix it.

Do you agree? If so, can we close the issue?
