### ISSUE TITLE
[Feature] Auto-approve add-ons submitted by admins

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#96]
### Is your feature request related to a problem?

When editing existing add-ons, admins have to approve their own edits. The same goes for when a manager submits a regular add-on.

### Describe the feature you'd like

Title.

**Comment by Juknum** [comment]
Admins shouldn't even be able to review their own stuff. See it as a security/no-rule bypass

**Comment by Pomi108** [comment]
No. My first point still stands. Add-on moderation still has to be performed, and that still requires admins to approve their own edits.

**Comment by Juknum** [comment]
Do you mean admins editing the add-on of somebody else?

**Comment by Pomi108** [comment]
Yes
