### ISSUE TITLE
[Feature] Add a way to delete (not deny) add-ons from the database

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#98]
### Is your feature request related to a problem?

Right now, it's only possible to deny add-ons. The issue is that they've now started piling up and there are more than a few duplicate/invalid addons that are never gonna get approved anyway that just get in the way.

### Describe the feature you'd like

There should be a button to delete an add-on completely.

**Comment by TheRolfFR** [comment]
We could delete them or add a new status like "archived" i don't know to move them out of the way

**Comment by Pomi108** [comment]
Yeah that works too, just anything to hide them

**Comment by TheRolfFR** [comment]
And https://github.com/Faithful-Resource-Pack/API/commit/928ebce3a0c258ffdab81e8e101cb2af1b91df21 for API changes
