### ISSUE TITLE
[Bug] Texture names in the gallery hover popup get cut off if they're too long

### ISSUE THREAD

**Issue by Pomi108** [Faithful-Resource-Pack/App#99]
### What happened?

Title.

### To reproduce

1. Go to the gallery
2. Find a texture with a long enough name (≥~18 characters)
3. See that the name is cut off

### Screenshot(s)

![obrazek](https://user-images.githubusercontent.com/59484948/189480311-9ed43d2f-58a5-4d9e-8e75-5313cc876650.png)

### Browser name and version

- Firefox 104.0.1

**Comment by TheRolfFR** [comment]
Yes I know, but I don't really know what to do, I must have a fixed length bu I need not to overflow too, and long texture names are a hell of a pain.

**Comment by Pomi108** [comment]
Wrap the line without any regard for words, just move the overflowing characters to the next line

**Comment by Pomi108** [comment]
Also maybe increase the max width to like 30 characters
